# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 798cd12e1abbf61210932d6b05c6318b57a6dd4e6f8a1e04a1150d3f62ba595889e004ba477b7ba42bf601d527de90639c0a9214c77fd09472889d037fe4bc0d

test:
  secret_key_base: 161315f6ecb6a68542775c63a72794302030a58f3f36124dc10b0f064830a764091f8356d1ea982e3baa8e54b9ef7eb2a621a84ea03bcbcc75c0aab6e851b345

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
